version: '3.8'

services:
  
  user_controller:
    depends_on:
      - user_service
    build:
      context: ./
      dockerfile: ./user_controller/Dockerfile
    container_name: user_controller
    expose:
      - 3000
    ports:
      - '3000:3000'
    environment:
      - USER_SERVICE_HOST=172.100.10.20
      - USER_SERVICE_PORT=50051
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.10

  user_service:
    depends_on:
      - user_repository
    build:
      context: ./
      dockerfile: ./user_service/Dockerfile
    container_name: user_service
    expose:
      - 50051
    ports:
      - '50051:50051'
    environment:
      - USER_REPOSITORY_HOST=172.100.10.30
      - USER_REPOSITORY_PORT=50061
      - INVENTORY_SERVICE_HOST=172.100.10.21
      - INVENTORY_SERVICE_PORT=50052
      - PAYMENT_SERVICE_HOST=172.100.10.25
      - PAYMENT_SERVICE_PORT=50055
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.20
  
  user_repository:
    restart: on-failure:10
    build:
      context: ./
      dockerfile: ./user_repository/Dockerfile
    container_name: user_repository
    expose:
      - 50061
    ports:
      - '50061:50061'
    environment:
      - MONGO_USER=db_access
      - MONGO_PASSWORD=VerySecureYesYes123
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.30
  
  inventory_controller:
    depends_on:
      - inventory_service
    build:
      context: ./
      dockerfile: ./inventory_controller/Dockerfile
    container_name: inventory_controller
    expose:
      - 3001
    ports:
      - '3001:3001'
    environment:
      - INVENTORY_SERVICE_HOST=172.100.10.21
      - INVENTORY_SERVICE_PORT=50052
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.11

  inventory_service:
    depends_on:
      - inventory_repository
    build:
      context: ./
      dockerfile: ./inventory_service/Dockerfile
    container_name: inventory_service
    expose:
      - 50052
    ports:
      - '50052:50052'
    environment:
      - INVENTORY_REPOSITORY_HOST=172.100.10.31
      - INVENTORY_REPOSITORY_PORT=50062
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.21

  inventory_repository:
    depends_on:
      - inventory_db
    restart: on-failure:10
    build:
      context: ./
      dockerfile: ./inventory_repository/Dockerfile
    container_name: inventory_repository
    expose:
      - 50062
    ports:
      - '50062:50062'
    volumes:
      - ./dataset/dataset.csv:/service/dataset/dataset.csv
    environment:
      - INVENTORY_DB_NAME=inventory_db
      - INVENTORY_DB_USER=db_access_inventory
      - INVENTORY_DB_PASSWORD=VerySecureYesYes123
      - INVENTORY_DB_HOST=172.100.10.41
      - INVENTORY_DB_PORT=5432
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.31

  inventory_db:
    image: postgres:latest
    command: postgres -c "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - 5432:5432
    volumes:
      - ./volumes/inventory_db:/var/lib/postgresql/data
      - ./custom_configs/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=VerySecureYesYes123
      - POSTGRES_USER=db_access_inventory
      - POSTGRES_DB=inventory_db
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.41

  review_controller:
    depends_on:
      - review_service
    build:
      context: ./
      dockerfile: ./review_controller/Dockerfile
    container_name: review_controller
    expose:
      - 3003
    ports:
      - '3003:3003'
    environment:
      - REVIEW_SERVICE_HOST=172.100.10.23
      - REVIEW_SERVICE_PORT=50053
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.13

  review_service:
    depends_on:
      - inventory_service
    build:
      context: ./
      dockerfile: ./review_service/Dockerfile
    container_name: review_service
    expose:
      - 50053
    ports:
      - '50053:50053'
    environment:
      - INVENTORY_SERVICE_HOST=172.100.10.21
      - INVENTORY_SERVICE_PORT=50052
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.23

  order_controller:
    build:
      context: ./
      dockerfile: ./order_controller/Dockerfile
    container_name: order_controller
    expose:
      - 3004
    ports:
      - '3004:3004'
    environment:
      - ORDER_SERVICE_HOST=172.100.10.24
      - ORDER_SERVICE_PORT=50054
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.14

  order_service:
    depends_on:
      - order_repository
      - inventory_service
    build:
      context: ./
      dockerfile: ./order_service/Dockerfile
    container_name: order_service
    expose:
      - 50054
    ports:
      - '50054:50054'
    environment:
      - ORDER_REPOSITORY_HOST=172.100.10.34
      - ORDER_REPOSITORY_PORT=50064
      - INVENTORY_SERVICE_HOST=172.100.10.21
      - INVENTORY_SERVICE_PORT=50052
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.24

  order_repository:
    restart: on-failure:10
    build:
      context: ./
      dockerfile: ./order_repository/Dockerfile
    container_name: order_repository
    expose:
      - 50064
    ports:
      - '50064:50064'
    environment:
      - MONGO_USER=db_access
      - MONGO_PASSWORD=SafestOrders
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.34
        
  payment_controller:
    build: 
      context: ./
      dockerfile: ./payment_controller/Dockerfile
    container_name: payment_controller
    expose:
      - 3005
    ports:
      - '3005:3005'
    environment:
      - PAYMENT_SERVICE_HOST=172.100.10.25
      - PAYMENT_SERVICE_PORT=50055
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.15
  
  payment_service:
    depends_on:
      - payment_repository
    build:
      context: ./
      dockerfile: ./payment_service/Dockerfile
    container_name: payment_service
    expose:
      - 50055
    ports:
      - '50055:50055'
    environment:
      - PAYMENT_REPOSITORY_HOST=172.100.10.35
      - PAYMENT_REPOSITORY_PORT=50065
      - ORDER_SERVICE_HOST=172.100.10.24
      - ORDER_SERVICE_PORT=50054
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.25
  
  payment_repository:
    restart: on-failure:10
    build:
      context: ./
      dockerfile: ./payment_repository/Dockerfile
    container_name: payment_repository
    expose:
      - 50065
    ports:
      - '50065:50065'
    environment:
      - MONGO_USER=db_access
      - MONGO_PASSWORD=SecurePayment123
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.35 

networks:
  brewstand-net:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.100.10.0/24