version: '3.8'

services:
  
  user_controller:
    depends_on:
      - user_service
    build:
      context: ./
      dockerfile: ./user_controller/Dockerfile
    container_name: user_controller
    expose:
      - 3000
    ports:
      - '3000:3000'
    environment:
      - USER_SERVICE_HOST=172.100.10.20
      - USER_SERVICE_PORT=50051
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.10

  user_service:
    depends_on:
      - user_repository
    build:
      context: ./
      dockerfile: ./user_service/Dockerfile
    container_name: user_service
    expose:
      - 50051
    ports:
      - '50051:50051'
    environment:
      - USER_REPOSITORY_HOST=172.100.10.30
      - USER_REPOSITORY_PORT=50061
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.20
  
  user_repository:
    restart: on-failure:10
    build:
      context: ./
      dockerfile: ./user_repository/Dockerfile
    container_name: user_repository
    expose:
      - 50061
    ports:
      - '50061:50061'
    environment:
      - MONGO_USER=db_access
      - MONGO_PASSWORD=VerySecureYesYes123
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.30

  inventory_repository:
    depends_on:
      - inventory_db
    restart: on-failure:10
    build:
      context: ./
      dockerfile: ./inventory_repository/Dockerfile
    container_name: inventory_repository
    expose:
      - 50062
    ports:
      - '50062:50062'
    volumes:
      - ./dataset/dataset.csv:/service/dataset/dataset.csv
    environment:
      - INVENTORY_DB_NAME=inventory_db
      - INVENTORY_DB_USER=db_access_inventory
      - INVENTORY_DB_PASSWORD=VerySecureYesYes123
      - INVENTORY_DB_HOST=172.100.10.41
      - INVENTORY_DB_PORT=5432
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.31

  inventory_db:
    image: postgres:latest
    command: postgres -c "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - 5432:5432
    volumes:
      - ./volumes/inventory_db:/var/lib/postgresql/data
      - ./custom_configs/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=VerySecureYesYes123
      - POSTGRES_USER=db_access_inventory
      - POSTGRES_DB=inventory_db
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.41

  review_service:
    depends_on:
      - inventory_repository
    build:
      context: ./
      dockerfile: ./review_service/Dockerfile
    container_name: review_service
    expose:
      - 50052
    ports:
      - '50052:50052'
    environment:
      - INVENTORY_REPOSITORY_HOST=172.100.10.31
      - INVENTORY_REPOSITORY_PORT=50062
    networks:
      brewstand-net:
        ipv4_address: 172.100.10.21

networks:
  brewstand-net:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.100.10.0/24