# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import payment_repository_pb2 as payment__repository__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment_service.proto\x12\x0fpayment_service\x1a\x18payment_repository.proto\"\xa7\x01\n\x15ProcessPaymentRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x12\n\nitems_name\x18\x04 \x03(\t\x12\x15\n\rfiscalAddress\x18\x05 \x01(\t\x12\x31\n\x0b\x63\x61rdDetails\x18\x06 \x01(\x0b\x32\x1c.payment_service.CardDetails\"F\n\x0b\x43\x61rdDetails\x12\x12\n\ncardNumber\x18\x01 \x01(\t\x12\x12\n\ncardExpiry\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61rdCvc\x18\x03 \x01(\t\"t\n\x16ProcessPaymentResponse\x12\x15\n\rresponse_code\x18\x01 \x01(\x05\x12\x11\n\tinvoiceId\x18\x02 \x01(\t\x12\x30\n\x07invoice\x18\x03 \x01(\x0b\x32\x1f.payment_repository.InvoiceData\"#\n\x0eInvoiceRequest\x12\x11\n\tinvoiceId\x18\x01 \x01(\t\"Z\n\x0fInvoiceResponse\x12\x15\n\rresponse_code\x18\x01 \x01(\x05\x12\x30\n\x07invoice\x18\x02 \x01(\x0b\x32\x1f.payment_repository.InvoiceData\"%\n\x13UserInvoicesRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"I\n\x14UserInvoicesResponse\x12\x31\n\x08invoices\x18\x01 \x03(\x0b\x32\x1f.payment_repository.InvoiceData2\xad\x02\n\x0ePaymentService\x12\x63\n\x0eProcessPayment\x12&.payment_service.ProcessPaymentRequest\x1a\'.payment_service.ProcessPaymentResponse\"\x00\x12Q\n\nGetInvoice\x12\x1f.payment_service.InvoiceRequest\x1a .payment_service.InvoiceResponse\"\x00\x12\x63\n\x12GetAllUserInvoices\x12$.payment_service.UserInvoicesRequest\x1a%.payment_service.UserInvoicesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROCESSPAYMENTREQUEST']._serialized_start=69
  _globals['_PROCESSPAYMENTREQUEST']._serialized_end=236
  _globals['_CARDDETAILS']._serialized_start=238
  _globals['_CARDDETAILS']._serialized_end=308
  _globals['_PROCESSPAYMENTRESPONSE']._serialized_start=310
  _globals['_PROCESSPAYMENTRESPONSE']._serialized_end=426
  _globals['_INVOICEREQUEST']._serialized_start=428
  _globals['_INVOICEREQUEST']._serialized_end=463
  _globals['_INVOICERESPONSE']._serialized_start=465
  _globals['_INVOICERESPONSE']._serialized_end=555
  _globals['_USERINVOICESREQUEST']._serialized_start=557
  _globals['_USERINVOICESREQUEST']._serialized_end=594
  _globals['_USERINVOICESRESPONSE']._serialized_start=596
  _globals['_USERINVOICESRESPONSE']._serialized_end=669
  _globals['_PAYMENTSERVICE']._serialized_start=672
  _globals['_PAYMENTSERVICE']._serialized_end=973
# @@protoc_insertion_point(module_scope)
