# THIS CODE WAS AUTO GENERATED BY SWAGGER EDITOR

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from utils import util


class ItemIdReviewBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, score: float=None):  # noqa: E501
        """ItemIdReviewBody - a model defined in Swagger

        :param score: The score of this ItemIdReviewBody.  # noqa: E501
        :type score: float
        """
        self.swagger_types = {
            'score': float
        }

        self.attribute_map = {
            'score': 'score'
        }
        self._score = score

    @classmethod
    def from_dict(cls, dikt) -> 'ItemIdReviewBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The itemId_review_body of this ItemIdReviewBody.  # noqa: E501
        :rtype: ItemIdReviewBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def score(self) -> float:
        """Gets the score of this ItemIdReviewBody.

        The user attributed rating for the beer batch, from 0 to 10.  # noqa: E501

        :return: The score of this ItemIdReviewBody.
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score: float):
        """Sets the score of this ItemIdReviewBody.

        The user attributed rating for the beer batch, from 0 to 10.  # noqa: E501

        :param score: The score of this ItemIdReviewBody.
        :type score: float
        """

        self._score = score
