openapi: 3.0.3
info:
  title: BrewStand_OrderAPI
  description: |-
    This is the definition of the REST API for the BrewStand Order Service. Here, users can view their orders and check their status
  version: 1.0.0
servers:
  - url: /
tags:
  - name: Order
    description: Supports operations related with the tracking of orders.
paths:
  /order/{orderId}:
    get:
      tags:
        - Order
      summary: Gets the details related to a specific order.
      description: Gets details such as cost, status and delivary address for a given order.
      operationId: orderHandler.getOrder
      parameters:
        - name: orderId
          in: path
          description: The ID of the order whose details we want to view.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/Order'
        '404':
          description: Requested order was not found.
  /order:
    get:
      tags:
        - Order
      summary: Gets all orders related to a user.
      description: Gets all orders related to a user.
      operationId: orderHandler.getOrders
      parameters:
        - name: userId
          in: query
          description: The id of the user whose orders we want to view
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : '#/components/schemas/Order'
            
        '404':
          description: Requested order was not found.
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
          description: The order id
        userId:
          type: string
          example: asd2a1da3qe1
          description: The id of the user associated with the order
        items:
          type: array
          items:
            type: object
            properties:
              itemID:
                type: integer
                format: int64
                example: 10
                description:  A unique identifier assigned to each batch of beer produced.
              volume:
                type: number
                format: double
                description: The volume of the item being acquired, in liters.
        shipDate:
          type: string
          format: date-time
          description: The date the order was sent to shipping
        status:
          type: string
          description: The status of the order
          example: approved
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
        destinationAddress:
          type: string
          example: Campo Grande 016, 1749-016 Lisboa
          description: The address to where the order will be sent.
 
    