# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import payment_repository_pb2 as payment__repository__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment_service.proto\x12\x0fpayment_service\x1a\x18payment_repository.proto\"\x89\x01\n\x0ePaymentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x10\n\x08items_id\x18\x04 \x03(\x05\x12\x32\n\x0c\x63\x61rd_details\x18\x05 \x01(\x0b\x32\x1c.payment_service.CardDetails\"I\n\x0b\x43\x61rdDetails\x12\x13\n\x0b\x63\x61rd_number\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61rd_expiry\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61rd_cvc\x18\x03 \x01(\t\"e\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x41\n\x0fpayment_details\x18\x02 \x01(\x0b\x32(.payment_repository.StorePaymentResponse\"$\n\x0eInvoiceRequest\x12\x12\n\ninvoice_id\x18\x01 \x01(\x05\"T\n\x0fInvoiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x30\n\x07invoice\x18\x02 \x01(\x0b\x32\x1f.payment_repository.InvoiceData2\xba\x01\n\x0ePaymentService\x12U\n\x0eProcessPayment\x12\x1f.payment_service.PaymentRequest\x1a .payment_service.PaymentResponse\"\x00\x12Q\n\nGetInvoice\x12\x1f.payment_service.InvoiceRequest\x1a .payment_service.InvoiceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYMENTREQUEST']._serialized_start=69
  _globals['_PAYMENTREQUEST']._serialized_end=206
  _globals['_CARDDETAILS']._serialized_start=208
  _globals['_CARDDETAILS']._serialized_end=281
  _globals['_PAYMENTRESPONSE']._serialized_start=283
  _globals['_PAYMENTRESPONSE']._serialized_end=384
  _globals['_INVOICEREQUEST']._serialized_start=386
  _globals['_INVOICEREQUEST']._serialized_end=422
  _globals['_INVOICERESPONSE']._serialized_start=424
  _globals['_INVOICERESPONSE']._serialized_end=508
  _globals['_PAYMENTSERVICE']._serialized_start=511
  _globals['_PAYMENTSERVICE']._serialized_end=697
# @@protoc_insertion_point(module_scope)
