# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import payment_service_pb2 as payment__service__pb2


class PaymentServiceStub(object):
    """The PaymentService handles processing payments and communicating with the Payment Repository Service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessPayment = channel.unary_unary(
                '/payment_service.PaymentService/ProcessPayment',
                request_serializer=payment__service__pb2.PaymentRequest.SerializeToString,
                response_deserializer=payment__service__pb2.PaymentResponse.FromString,
                )
        self.GetInvoice = channel.unary_unary(
                '/payment_service.PaymentService/GetInvoice',
                request_serializer=payment__service__pb2.InvoiceRequest.SerializeToString,
                response_deserializer=payment__service__pb2.InvoiceResponse.FromString,
                )


class PaymentServiceServicer(object):
    """The PaymentService handles processing payments and communicating with the Payment Repository Service.
    """

    def ProcessPayment(self, request, context):
        """Processes a payment and returns a response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInvoice(self, request, context):
        """Retrieves an invoice for a particular order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=payment__service__pb2.PaymentRequest.FromString,
                    response_serializer=payment__service__pb2.PaymentResponse.SerializeToString,
            ),
            'GetInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvoice,
                    request_deserializer=payment__service__pb2.InvoiceRequest.FromString,
                    response_serializer=payment__service__pb2.InvoiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment_service.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """The PaymentService handles processing payments and communicating with the Payment Repository Service.
    """

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment_service.PaymentService/ProcessPayment',
            payment__service__pb2.PaymentRequest.SerializeToString,
            payment__service__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment_service.PaymentService/GetInvoice',
            payment__service__pb2.InvoiceRequest.SerializeToString,
            payment__service__pb2.InvoiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
