apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: inventory-db-secret
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/cloud-computing-project-416422/secrets/Inventory_db/versions/1"
        path: "inventory-db-password"