apiVersion: v1
kind: PersistentVolume
metadata:
  name: brewstand-dataset-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: bucket-storage
  claimRef:
    namespace: default
    name: brewstand-dataset-pvc
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: brewstand-datset
    volumeAttributes:
      gcsfuseLoggingSeverity: warning
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brewstand-dataset-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: brewstand-dataset-pv
  storageClassName: bucket-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-repository
  template:
    metadata:
      labels:
        app: inventory-repository
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      containers:
        - name: inventory-repository
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/inventory_repository:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50062
          env:
            - name: INVENTORY_DB_NAME
              value: "inventory_db"
            - name: INVENTORY_DB_USER
              value: "db_access_inventory"
            - name: INVENTORY_DB_PASSWORD
              value: "VerySecureYesYes123"
            - name: INVENTORY_DB_HOST
              value: "postgres"
            - name: INVENTORY_DB_PORT
              value: "5432"
            - name: DATASET_URL
              value: "/data/dataset.csv"
          volumeMounts:
            - name: brewstand-dataset
              mountPath: /data
              readOnly: true
      serviceAccountName: brewstand-sa
      volumes:
        - name: brewstand-dataset
          persistentVolumeClaim:
            claimName: brewstand-dataset-pvc
            readOnly: true
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: inventory-repo-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: inventory-repository
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-repository
  labels:
    app: inventory-repository
spec:
  type: ClusterIP
  ports:
    - port: 50062
  selector:
    app: inventory-repository