apiVersion: v1
kind: PersistentVolume
metadata:
  name: brewstand-dataset-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: bucket-storage
  claimRef:
    namespace: default
    name: brewstand-dataset-pvc
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: brewstand-datset
    volumeAttributes:
      gcsfuseLoggingSeverity: warning
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brewstand-dataset-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: brewstand-dataset-pv
  storageClassName: bucket-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-repository
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: inventory-repository
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      containers:
        - name: inventory-repository
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/inventory_repository:latest'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 50062
          env:
            - name: INVENTORY_DB_NAME
              value: "inventory_db"
            - name: INVENTORY_DB_USER
              value: "db_access_inventory"
            - name: INVENTORY_DB_PASSWORD
              value: "VerySecureYesYes123"
            - name: INVENTORY_DB_HOST
              value: "postgres"
            - name: INVENTORY_DB_PORT
              value: "5432"
            - name: DATASET_URL
              value: "/data/dataset.csv"
          volumeMounts:
            - name: brewstand-dataset
              mountPath: /data
              readOnly: true
      serviceAccountName: brewstand-sa
      volumes:
        - name: brewstand-dataset
          persistentVolumeClaim:
            claimName: brewstand-dataset-pvc
            readOnly: true
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: inventory-repo-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: inventory-repository
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-repository
  labels:
    app: inventory-repository
spec:
  type: ClusterIP
  ports:
    - port: 50062
  selector:
    app: inventory-repository
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/inventory_service:latest'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 50052
          env:
            - name: INVENTORY_REPOSITORY_HOST
              value: "inventory-repository"
            - name: INVENTORY_REPOSITORY_PORT
              value: "50062"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: inventory-service-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: inventory-service
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: 50052
  selector:
    app: inventory-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-controller
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: inventory-controller
    spec:
      containers:
        - name: inventory-controller
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/inventory_controller:latest'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 3001
          env:
            - name: INVENTORY_SERVICE_HOST
              value: "inventory-service"
            - name: INVENTORY_SERVICE_PORT
              value: "50052"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: inventory-controller-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: inventory-controller
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-controller
  labels:
    app: inventory-controller
spec:
  type: ClusterIP
  ports:
    - port: 3001
  selector:
    app: inventory-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-controller
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: user-controller
    spec:
      containers:
        - name: user-controller
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/user_controller:latest'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 3002
          env:
            - name: USER_SERVICE_HOST
              value: "user-service"
            - name: USER_SERVICE_PORT
              value: "50051"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: user-controller-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: user-controller
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: user-controller
  labels:
    app: user-controller
spec:
  type: ClusterIP
  ports:
    - port: 3002
  selector:
    app: user-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/user_service:latest'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 50051
          env:
            - name: USER_REPOSITORY_HOST
              value: "user-repository"
            - name: USER_REPOSITORY_PORT
              value: "50061"
            - name: INVENTORY_SERVICE_HOST
              value: "inventory-service"
            - name: INVENTORY_SERVICE_PORT
              value: "50052"
            - name: PAYMENT_SERVICE_HOST
              value: "50055"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: user-service-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: user-service
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
    - port: 50051
  selector:
    app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-repository
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: user-repository
    spec:
      containers:
        - name: user-repository
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/user_repository:latest'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 50061
          env:
            - name: MONGO_USER
              value: "db_access"
            - name: MONGO_PASSWORD
              value: "VerySecureYesYes123"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: user-repository-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: user-repository
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: user-repository
  labels:
    app: user-repository
spec:
  type: ClusterIP
  ports:
    - port: 50061
  selector:
    app: user-repository
