apiVersion: v1
kind: PersistentVolume
metadata:
  name: brewstand-dataset-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: bucket-storage
  claimRef:
    namespace: default
    name: brewstand-dataset-pvc
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: brewstand-datset
    volumeAttributes:
      gcsfuseLoggingSeverity: warning
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brewstand-dataset-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: brewstand-dataset-pv
  storageClassName: bucket-storage