apiVersion: v1
data:
  oauth2-proxy.cfg: |-
    provider="oidc"
    oidc_issuer_url="https://dev-gcr7j33oe3lkm2f4.us.auth0.com/"
    client_id="http://brewstand-api/"
    http_address="0.0.0.0:4180"
    upstreams="file:///dev/null"
    email_domains=["*"]
    skip_jwt_bearer_tokens=true

kind: ConfigMap
metadata:
  name: oauth2-proxy-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "oauth-proxy"
  template:
    metadata:
      labels:
        app: oauth-proxy
    spec:
      volumes:
        - name: oauth2-proxy-config
          configMap:
            name: oauth2-proxy-config
      containers:
      - name: oauth-proxy
        image: "quay.io/oauth2-proxy/oauth2-proxy:latest"
        ports:
        - containerPort: 4180
        env:
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secret
                key: OAUTH2_PROXY_COOKIE_SECRET
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secret
                key: OAUTH2_PROXY_CLIENT_SECRET
        volumeMounts:
        - name: oauth2-proxy-config
          mountPath: /etc/oauth2-proxy.cfg
          subPath: oauth2-proxy.cfg
        args:
          - --config=/etc/oauth2-proxy.cfg

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
spec:
  type: ClusterIP
  selector:
    app: oauth-proxy
  ports:
  - name: http-oauthproxy
    port: 4180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: oauth-proxy
            port:
              number: 4180
        path: /oauth2
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/auth-signin: http://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://$host/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /user-api/user/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-controller
            port:
              number: 3002
      - path: /review-api/items.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: review-controller
            port:
              number: 3003
      - path: /order-api/order.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: order-controller
            port:
              number: 3004
      - path: /payment-api/billing.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: payment-controller
            port:
              number: 3005
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /inventory-api/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: inventory-controller
            port:
              number: 3001
      - path: /user-api/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-controller
            port:
              number: 3002
      - path: /review-api/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: review-controller
            port:
              number: 3003
      - path: /order-api/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: order-controller
            port:
              number: 3004
      - path: /payment-api/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: payment-controller
            port:
              number: 3005