
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: inventory_db
  POSTGRES_USER: db_access_inventory
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: brewstand-sa  # Moved this line here
      containers:
        - name: postgres
          image: 'postgres:latest'
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
          stdin: true
          stdinOnce: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
            - mountPath: "/var/secrets"
              name: mysecret
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
        - name: mysecret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "inventory-db-secret"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: postgres-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: postgres
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: brewstand-dataset-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: bucket-storage
  claimRef:
    namespace: default
    name: brewstand-dataset-pvc
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: brewstand-datset
    volumeAttributes:
      gcsfuseLoggingSeverity: warning
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brewstand-dataset-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: brewstand-dataset-pv
  storageClassName: bucket-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-repository
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: inventory-repository
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      initContainers:
        - name: copy-secrets
          image: busybox
          command: ['sh', '-c', 'cp /mnt/secrets/* /etc/secrets/ && echo "Secrets copied!"']
          volumeMounts:
            - name: mysecret
              mountPath: "/mnt/secrets"
            - name: secret-env
              mountPath: "/etc/secrets"
      containers:
        - name: inventory-repository
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/inventory_repository:latest'
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 50062
          env:
            - name: INVENTORY_DB_NAME
              value: "inventory_db"
            - name: INVENTORY_DB_USER
              value: "db_access_inventory"
            - name: INVENTORY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: inventory-db-password
            - name: INVENTORY_DB_HOST
              value: "postgres"
            - name: INVENTORY_DB_PORT
              value: "5432"
            - name: DATASET_URL
              value: "/data/dataset.csv"
          volumeMounts:
            - name: brewstand-dataset
              mountPath: /data
              readOnly: true
            - mountPath: "/var/secrets"
              name: secret-env
          livenessProbe:
            tcpSocket:
              port: 50062
            periodSeconds: 12
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 50062
            periodSeconds: 11
          startupProbe:
            tcpSocket:
              port: 50062
            failureThreshold: 30
            periodSeconds: 10
      serviceAccountName: brewstand-sa
      volumes:
        - name: brewstand-dataset
          persistentVolumeClaim:
            claimName: brewstand-dataset-pvc
            readOnly: true
        - name: mysecret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "inventory-db-secret"
        - name: secret-env
          emptyDir: {}
          
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: inventory-repo-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: inventory-repository
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-repository
  labels:
    app: inventory-repository
spec:
  type: ClusterIP
  ports:
    - port: 50062
  selector:
    app: inventory-repository
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/inventory_service:latest'
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 50052
          env:
            - name: INVENTORY_REPOSITORY_HOST
              value: "inventory-repository"
            - name: INVENTORY_REPOSITORY_PORT
              value: "50062"
          livenessProbe:
            tcpSocket:
              port: 50052
            periodSeconds: 12
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 50052
            periodSeconds: 11
          startupProbe:
            tcpSocket:
              port: 50052
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: inventory-service-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: inventory-service
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: 50052
  selector:
    app: inventory-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-controller
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: inventory-controller
    spec:
      containers:
        - name: inventory-controller
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/inventory_controller:latest'
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 3001
          env:
            - name: INVENTORY_SERVICE_HOST
              value: "inventory-service"
            - name: INVENTORY_SERVICE_PORT
              value: "50052"
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            periodSeconds: 12
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            periodSeconds: 11
          startupProbe:
            httpGet:
              path: /
              port: 3001
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: inventory-controller-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: inventory-controller
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-controller
  labels:
    app: inventory-controller
spec:
  type: NodePort
  ports:
    - port: 3001
  selector:
    app: inventory-controller
