apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-controller
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: order-controller
    spec:
      containers:
        - name: order-controller
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/order_controller:latest'
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 3004
          env:
            - name: ORDER_SERVICE_HOST
              value: "order-service"
            - name: ORDER_SERVICE_PORT
              value: "50054"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: order-controller-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: order-controller
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: order-controller
  labels:
    app: order-controller
spec:
  type: ClusterIP
  ports:
    - port: 3004
  selector:
    app: order-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/order_service:latest'
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 50054
          env:
            - name: ORDER_REPOSITORY_HOST
              value: "order-repository"
            - name: ORDER_REPOSITORY_PORT
              value: "50064"
            - name: INVENTORY_SERVICE_HOST
              value: "inventory-service"
            - name: INVENTORY_SERVICE_PORT
              value: "50052"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: order-service-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: order-service
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
    - port: 50054
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-repository
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: order-repository
    spec:
      containers:
        - name: order-repository
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/order_repository:latest'
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 50064
          env:
            - name: MONGO_USER
              value: "db_access"
            - name: MONGO_PASSWORD
              value: "SafestOrders"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: order-repository-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: order-repository
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: order-repository
  labels:
    app: order-repository
spec:
  type: ClusterIP
  ports:
    - port: 50064
  selector:
    app: order-repository