scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']

    - job_name: inventory-controller
      scrape_interval: 5s
      static_configs:
        - targets: ['inventory-controller:3001']
  
    - job_name: user-controller
      scrape_interval: 5s
      static_configs:
        - targets: ['user-controller:3002']
    
    - job_name: order-controller
      scrape_interval: 5s
      static_configs:
        - targets: ['order-controller:3004']

