apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-controller
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: review-controller
    spec:
      containers:
        - name: review-controller
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/review_controller:latest'
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 3003
          env:
            - name: REVIEW_SERVICE_HOST
              value: "review-service"
            - name: REVIEW_SERVICE_PORT
              value: "50053"
          livenessProbe:
            httpGet:
              path: /
              port: 3003
            periodSeconds: 12
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3003
            periodSeconds: 11
          startupProbe:
            httpGet:
              path: /
              port: 3003
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: review-controller-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: review-controller
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: review-controller
  labels:
    app: review-controller
spec:
  type: ClusterIP
  ports:
    - port: 3003
  selector:
    app: review-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: 'europe-southwest1-docker.pkg.dev/cloud-computing-project-416422/brewstand-repo/review_service:latest'
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "50m"
          ports:
            - containerPort: 50053
          env:
            - name: INVENTORY_SERVICE_HOST
              value: "inventory-service"
            - name: INVENTORY_SERVICE_PORT
              value: "50052"
          livenessProbe:
            tcpSocket:
              port: 50053
            periodSeconds: 12
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 50053
            periodSeconds: 11
          startupProbe:
            tcpSocket:
              port: 50053
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: review-service-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: review-service
 minReplicas: 2
 maxReplicas: 4
 targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  labels:
    app: review-service
spec:
  type: ClusterIP
  ports:
    - port: 50053
  selector:
    app: review-service