openapi: 3.0.3
info:
  title: BrewStand_PaymentAPI
  description: |-
    This is the definition of the REST API for the BrewStand Payment Service. Here, it is processed the payment of users and they receive their invoices.
  version: 1.0.0
servers:
  - url: /
tags:
  - name: Billing
    description: Supports operations related with the payment and invoice of orders. 
paths:
  /billing/{invoiceId}:
    get: 
      tags:
        - Billing
      summary: Gets the details of a specific invoice.
      description: Gets the details of a specific invoice.
      operationId: paymentHandler.getInvoice
      parameters:
        - name: invoiceId
          in: path
          description: The ID of the invoice whose details we want to view.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/Invoice'
        '404':
          description: Requested invoice was not found
  /billing:
    get: 
      tags:
        - Billing
      summary: Gets all invoices related to a user.
      description: Gets all invoices related to a user.
      operationId: paymentHandler.getInvoices
      parameters:
        - name: userId
          in: query
          description: The ID of the user whose invoices we want to see
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : '#/components/schemas/Invoice'
        '404':
          description: Requested invoice was not found
components:
  schemas:
    Invoice:
      type: object
      properties:
        invoiceID:
          type: integer
          format: int64
          example: 10
          description:  A unique identifier assigned to each invoice processed.
        price:
          type: number
          format: double
          example: 335.5
          description: The total cost for the order.
        orderID:
          type: integer
          format: int64
          example: 10
          description: The order id. Used for tracking purposes.
        customerID:
          type: integer
          format: int64
          example: 10
          description: The id of the user who initiated the payment process.
        fiscalAddress:
          type: string
          example: Campo Grande 016, 1749-016 Lisboa
          description: The address used for billing purposes.
        details:
          type: string
          description: Optional details and extra notes about the order.

