name: Unit Tests

permissions:
    checks: write
    contents: read
    pull-requests: write

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v4

    # Build Tests

    - name: Build Payment Repository Test Suite
      run: docker build -t payment-repository-test:latest -f payment_repository/Dockerfile.test .

    - name: Build Payment Service Test Suite
      run: docker build -t payment-service-test:latest -f payment_service/Dockerfile.test .

    - name: Build Review Service Test Suite
      run: docker build -t review-service-test:latest -f review_service/Dockerfile.test .

    - name: Build User Repository Test Suite
      run: docker build -t user-repository-test:latest -f user_repository/Dockerfile.test .

    - name: Build User Service Test Suite
      run: docker build -t user-service-test:latest -f user_service/Dockerfile.test .

    - name: Build Inventory Service Test Suite
      run: docker build -t inventory-service-test:latest -f inventory_service/Dockerfile.test .
    
    - name: Build Inventory Repository Test Suite
      run: docker build -t inventory-repository-test:latest -f inventory_repository/Dockerfile.test .

    - name: Build Order Service Test Suite
      run: docker build -t order-service-test:latest -f order_service/Dockerfile.test .

    - name: Build Order Repository Test Suite
      run: docker build -t order-repository-test:latest -f order_repository/Dockerfile.test .
    
    # Run Tests

    - name: Run Payment Repository Test Suite
      run: docker run -v ./test_results:/service/test-reports payment-repository-test:latest

    - name: Run Payment Service Test Suite
      run: docker run -v ./test_results:/service/test-reports payment-service-test:latest

    - name: Run Review Service Test Suite
      run: docker run -v ./test_results:/service/test-reports review-service-test:latest

    - name: Run User Repository Test Suite
      run: docker run -v ./test_results:/service/test-reports user-repository-test:latest

    - name: Run User Service Test Suite
      run: docker run -v ./test_results:/service/test-reports user-service-test:latest

    - name: Run Inventory Service Test Suite
      run: docker run -v ./test_results:/service/test-reports inventory-service-test:latest

    - name: Run Inventory Repository Test Suite
      run: docker run -v ./test_results:/service/test-reports inventory-repository-test:latest

    - name: Run Order Service Test Suite
      run: docker run -v ./test_results:/service/test-reports order-service-test:latest
    
    - name: Run Order Repository Test Suite
      run: docker run -v ./test_results:/service/test-reports order-repository-test:latest

    # Save Test Results

    - name: Save JUnit Reports
      uses: mikepenz/action-junit-report@v4
      with:
        fail_on_failure: true
        include_passed: true
        report_paths: '**/test_results/*_tests.xml'
            
